[package]
name = "aegis_engine"
version = "0.1.0"
edition = "2021"
authors = ["Shaza"]
description = "Pure Vulkan 1.4 From Scratch 3D Engine for VR and Mobile"

[dependencies]
# Direct Vulkan 1.4 C API Bindings (Zero Middleware)
ash = "0.38"
ash-window = "0.13"
raw-window-handle = "0.6"

# Windowing & Events (Minimal sans backend lourds Wayland/Adwaita/Fonts)
winit = { version = "0.30", default-features = false, features = ["x11", "rwh_06"] }

# Math & Data Packing (0 dépendances secondaires)
glam = "0.29"
bytemuck = { version = "1.18", features = ["derive"] }

# Logging & Diagnostic
log = "0.4"
env_logger = "0.11"

[build-dependencies]
# Pure-Rust Shader Compiler (GLSL -> Vulkan 1.4 SPIR-V au build time uniquement)
naga = { version = "23.1", features = ["glsl-in", "spv-out"] }



